max_width = 80
condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
struct_field_align_threshold = 20
# The following seems to be added in a nightly version greater than ours
# use_field_init_shorthand = true
wrap_comments = true
