[package]
name = "blackberry"
version = "0.1.0"
authors = ["Michael Gerakis <mgerakis@bu.com>"]

[dependencies]
stack-vec = { path = "stack-vec" }
xmodem = { path = "xmodem" }
volatile = { path = "volatile" }
ttywrite = { path = "ttywrite" }

[workspace]
