[package]
name = "bootloader"
version = "0.1.0"
authors = ["Michael Gerakis <mgerakis@bu.com>"]

[lib]
path = "src/bootloader.rs"
crate-type = ["staticlib"]

[dependencies]
pi = { path = "../pi" }
xmodem = { path = "../xmodem" }
